config/routes.rb
Rails.application.routes.draw do
  root 'conversations#index'
  devise_for :users
  resources :conversations do
    resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user1, class_name: 'User'
  belongs_to :user2, class_name: 'User'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :sender, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_conversation, only: [:show, :edit, :update, :destroy]

  # GET /conversations
  # GET /conversations.json
  def index
    as1 = Conversation.where(user1: current_user)
    as2 = Conversation.where(user2: current_user)
    @conversations = as1 | as2
  end

  # GET /conversations/1
  # GET /conversations/1.json
  def show
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations
  # POST /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)
    @conversation.user1 = current_user

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to conversation_messages_url(@conversation), notice: 'Conversation was successfully created.' }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1
  # PATCH/PUT /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation was successfully updated.' }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1
  # DELETE /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conversation_params
      params.require(:conversation).permit(:user2_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_conversation
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.where(conversation_id: params[:conversation_id])
    @new_message = Message.new
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.conversation = @conversation
    @message.sender = current_user

    respond_to do |format|
      if @message.save
        format.html { redirect_to conversation_messages_url(@conversation), notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to conversation_messages_url(@conversation), notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to conversation_messages_url(@conversation), notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end
    
    def set_conversation
      @conversation = Conversation.find(params[:conversation_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  
  def emoji_display(content)
    content.gsub(':smile:', '&#9786;')
    content.gsub(':laughing:', '&#9786;')
    content.gsub(':stuck_out_tongue:', '&#9786;')
    content.gsub(':worried:', '&#9786;')
    content.gsub(':wink:', '&#9786;')
  end
end

app/views/conversations/_form.html.erb
<%= form_with(model: conversation, local: true) do |form| %>
  <% if conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
      <% conversation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user2_id, 'Select Contact:' %>
    <%= form.collection_select :user2_id, User.where.not(id: current_user.id), :id, :name, id: :conversation_user2_id %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit 'Start Conversation!', class: "btn btn-primary" %>
  </div>
  <br>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chats</h1>

<hr />

<div class="row">
  <div class="offset-md-2 col-md-8">
    <% @conversations.each do |conversation| %>
      <div class="card card-body bg-light">
        <h4><%= link_to current_user == conversation.user1 ? 
            conversation.user2.name : conversation.user1.name, 
            conversation_messages_path(conversation) %></h4>
        <p><%= truncate(Message.where(conversation_id: conversation.id).last.content, length: 30) %></p>
        <p>
          <span class="quiet"><small>Last message <%= time_ago_in_words(Message.where(conversation_id: conversation.id).last.created_at) %> ago.</small></span>
        </p>
      </div>
    <% end %>
  </div>
</div>

<br>

<%= link_to 'New Conversation', new_conversation_path, class: "btn btn-primary" %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User1:</strong>
  <%= @conversation.user1 %>
</p>

<p>
  <strong>User2:</strong>
  <%= @conversation.user2 %>
</p>

<%= link_to 'Edit', edit_conversation_path(@conversation) %> |
<%= link_to 'Back', conversations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whomsapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <div class="header">
    <h1 align="left">WhomsApp</h1>
    <p align="right">
      <% if user_signed_in? %>
        Hello <strong><%= current_user.name %></strong>!
        <%= link_to('Edit account', edit_user_registration_path) %> |
        <%= link_to 'Logout', destroy_user_session_path, method: :delete  %>
      <% else %>
        <%= link_to('Sign up', new_user_registration_path) %> |
        <%= link_to('Login', new_user_session_path) %>
      <% end %>
    </p>
  </div>
      
  <div class="container" align="center">
    <body>
      <%= yield %>
    </body>
  </div>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: [@conversation, message], local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="control-label col-md-4">
      <%= form.label :content, 'Enter your message:' %>
    </div>
    <div class="col-md-8">
      <%= form.text_area :content, rows: 10, class: "form-control", placeholder: "Enter your message.", id: :message_content %>
    </div>
  </div>
  
  <div class="form-group">
    <%= form.submit 'Send', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chat with <%= current_user == @conversation.user1 ? 
            @conversation.user2.name : @conversation.user1.name%></h1>
<hr />
<br>

  <% @messages.each do |message| %>
    <% if current_user.id == message.sender_id %>
      <div class="row">
        <div class="offset-md-4 col-md-8">
          <div class="card card-body bg-light">
            <p><%= message.content %></p>
            <span class="quiet"><small><%= message.created_at.to_date %></small></span>
          </div>
        </div>
      </div>
    <% else %>
      <div class="row">
        <div class="col-md-8">
          <div class="card card-body">
            <p><%= message.content %></p>
            <span class="quiet"><small><%= message.created_at.to_date %></small></span> 
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

<hr />      
<br>

<%= render 'form', message: @new_message %>

<br>

<%= link_to 'Back to Conversations', conversations_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', conversation_messages_path(@conversation) %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Conversation:</strong>
  <%= @message.conversation %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @message.sender %>
</p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/shared/_title.html.erb
<h1><%= title.capitalize %></h1>